### ISSUE TITLE
Tests fail to compile: use of undeclared identifier 'ASSERT_DEATH'

### ISSUE THREAD

**Issue by yurivict** [flexible-collision-library/fcl#549] opened 2021-09-15 19:20 UTC
```
/disk-samsung/freebsd-ports/math/fcl/work/fcl-0.7.0/test/narrowphase/detail/convexity_based_algorithm/test_gjk_libccd-inl_gjk_doSimplex2.cpp:289:3: error: use of undeclared identifier 'ASSERT_DEATH'
  ASSERT_DEATH(doSimplex2(&line_, &dir_),
  ^
/disk-samsung/freebsd-ports/math/fcl/work/fcl-0.7.0/test/narrowphase/detail/convexity_based_algorithm/test_gjk_libccd-inl_gjk_doSimplex2.cpp:303:3: error: use of undeclared identifier 'ASSERT_DEATH'
  ASSERT_DEATH(doSimplex2(&line_, &dir_),
  ^
/disk-samsung/freebsd-ports/math/fcl/work/fcl-0.7.0/test/narrowphase/detail/convexity_based_algorithm/test_gjk_libccd-inl_gjk_doSimplex2.cpp:317:3: error: use of undeclared identifier 'ASSERT_DEATH'
  ASSERT_DEATH(doSimplex2(&line_, &dir_),
  ^
```

Version: 0.7.0
clang-11
OS: FreeBSD 13

**Comment by sherm1** [comment] 2021-09-15 20:09
I _think_ that's a GTEST version issue. Maybe FreeBSD has an old version?

**Comment by jwnimmer-tri** [comment] 2021-09-15 20:16
See #443 / #396 / #358 / #354 / etc.

**Comment by yurivict** [comment] 2021-09-15 20:28
The currently used googletest is googletest-1.11.0.

**Comment by sherm1** [comment] 2021-09-15 21:44
Oh, per #443 fcl has its own out-of-date copy of gtest :(. If you can get it to use the FreeBSD one instead it would be fine.
I'll close this as a duplicate of #443 and others (thanks, @jwnimmer-tri). Not clear to me why we don't have this problem in other builds though.

**Closed** 2021-09-15 21:44 UTC
