### ISSUE TITLE
Fails to build: use of undeclared identifier 'ASSERT_DEATH'

### ISSUE THREAD

**Issue by yurivict** [flexible-collision-library/fcl#358] opened 2018-12-23 18:22 UTC
```
/wrkdirs/usr/ports/math/fcl/work/fcl-0.5.0-307-g7f85d6a/test/narrowphase/detail/convexity_based_algorithm/test_gjk_libccd-inl_epa.cpp:428:3: error: use of undeclared identifier 'ASSERT_DEATH'
  ASSERT_DEATH(
  ^
```

**Comment by sherm1** [comment] 2018-12-23 21:10
That's a Google test macro -- do you perhaps have an old version?

I'm not clear about the commit you referenced -- it doesn't seem to contain ASSERT_DEATH. Are you saying that caused the problem though?

**Comment by jwnimmer-tri** [comment] 2020-02-13 14:24
See https://github.com/google/googletest/blob/6f5fd0d7199b9a19faa9f499ecc266e6ae0329e7/googletest/include/gtest/internal/gtest-port.h#L587-L596

I think that (due to lack of `clone`?), the FreeBSD build of googletest does not provide the death-test capability.

**Comment by jwnimmer-tri** [comment] 2020-02-13 14:27
Though per https://github.com/google/googletest/commit/b215e30cadd11db7c9f378b57ffecce92aacce37 from 2015 it looks like it should have been working?

**Comment by jwnimmer-tri** [comment] 2021-09-15 21:49
@sherm1 please close as duplicate of #443?

**Closed** 2021-09-15 22:01 UTC
