### ISSUE TITLE
error: missing binary operator before token "("

### ISSUE THREAD

**Issue by dblanm** [flexible-collision-library/fcl#132] opened 2016-06-20 12:44 UTC
When making make in the build directory, using sudo make, make or make -j4
It gives me the error 
home.../fcl/octree.h error: missing binary operator before token "("
 #if OCTOMAP_VERSION_AT_LEAST(1,8,0)
                                                            ^

.... and it follows 

I change it to  #if OCTOMAP_VERSION_AT_LEAST(1.8.0)
but it didn't worked
Anyone with same problem that knows how to fix it?

Thanks in advance!

**Comment by dblanm** [comment] 2016-06-20 12:49
The code failing is this one:

 /// @return ptr to child number childIdx of node
  OcTreeNode* getNodeChild(OcTreeNode* node, unsigned int childIdx)
  { 
#if OCTOMAP_VERSION_AT_LEAST(1,8,0)
    return tree->getNodeChild(node, childIdx);
#else
    return node->getChild(childIdx);
#endif
} 

I have to say that I have installed last version of octomap, and checked it in /usr/local/share/octomap/package.xml

**Comment by jslee02** [comment] 2016-06-20 12:51
Could you try a clean build [as we did](https://github.com/flexible-collision-library/fcl/pull/129#issuecomment-226519520)?

**Comment by dblanm** [comment] 2016-06-20 13:06
I am sorry but I am a bit new modifying this.
I modified the fcl/config.h.in and added:
#if FCL_HAVE_OCTOMAP
  #define OCTOMAP_MAJOR_VERSION @OCTOMAP_MAJOR_VERSION@
  #define OCTOMAP_MINOR_VERSION @OCTOMAP_MINOR_VERSION@
  #define OCTOMAP_PATCH_VERSION @OCTOMAP_PATCH_VERSION@

  #define OCTOMAP_VERSION_AT_LEAST(x,y,z) \
    (OCTOMAP_MAJOR_VERSION > x || (OCTOMAP_MAJOR_VERSION >= x && \
    (OCTOMAP_MINOR_VERSION > y || (OCTOMAP_MINOR_VERSION >= y && \
    OCTOMAP_PATCH_VERSION >= z))))

  #define OCTOMAP_VERSION_AT_MOST(x,y,z) \
    (OCTOMAP_MAJOR_VERSION < x || (OCTOMAP_MAJOR_VERSION <= x && \
    (OCTOMAP_MINOR_VERSION < y || (OCTOMAP_MINOR_VERSION <= y && \
    OCTOMAP_PATCH_VERSION <= z))))
#endif // FCL_HAVE_OCTOMAP

and also included <fcl/config.h> (tested also fcl/config.h.in) in octree.h, and still have the same error.
What am I missing?

**Comment by jslee02** [comment] 2016-06-20 13:18
First, you wouldn't include `config.h.in` but `config.h` which is [generated by CMake](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/CMakeLists.txt#L7).

To clarify, do you mean the current master branch couldn't be built on your system? Why are you modifying `config.h.in`? 

Also, could you elaborate what you modified in `config.h.in`? Because I can't see any difference between what you posted and [the original `config.h.in`](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/config.h.in).

**Comment by dblanm** [comment] 2016-06-20 13:29
As you said, I couldn't built the master branch. I downloaded it again and changed octree.h before making cmake and the error still occurs.

**Comment by jslee02** [comment] 2016-06-20 13:34
Couldn't build it as you downloaded without any modification?

And, why are you changing `octree.h` again?

**Comment by dblanm** [comment] 2016-06-20 13:46
No, I couldn't because it gives me the error I first posted.

And I was changing octree.h to add the config.h to see it that corrected the error, but it didn't work. What I did was to add the config and to change OCTOMAP_VERSION_AT_LEAST(1,8,0) for OCTOMAP_VERSION_AT_LEAST(1.8.0). (, for .)

**Comment by jvgomez** [comment] 2016-06-21 14:17
This is the same problem I was having when I updated the PR. However, in the CI and for @jslee02 it worked fine. Perhaps is something related to the compiler? I am using `gcc version 4.8.5 (Ubuntu 4.8.5-2ubuntu1~14.04.1) `

**Comment by pbarragan** [comment] 2016-06-29 19:28
Hi, I also ran into this problem after trying to make a clean clone of FCL. I eventually had to try to force compilation ignoring octomap to get it to work (by changing CMakeCache.txt because I didn't know how to do it the right way). FCL works now, but I'm not sure why I got this error or how I would get around it if I wanted to use octomap. Any ideas on the compiler issue? I am using `gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4`. Is this problem an error with just the files included in FCL or could it have to do with the octomap package or other dependencies?

**Comment by jvgomez** [comment] 2016-06-29 20:53
@pbarragan I introduced recently this issue :( Since Octomap has changed the API, I wanted to make FCL able to work with both Octomap version >=1.8.0 and <1.8.0, that is why those compilation-time macros are introduced. It was not working on my computer (I tried many many different things), but for @jlsee02 it worked, and also in the CI. Surprisingly, I was even able to create a debian package out of it in my computer. 

@jslee02 which compiler did you use? Because Iused GCC4.8.4 as well. What does the CI use? I guess that, in any case, we should modify this to a simple #define OCTOMAP_GREATER_THAN_1_8 for instance. If you agree I will carry out the changes asap.

**Comment by jslee02** [comment] 2016-06-29 21:15
I'm using `gcc (Ubuntu 4.8.5-2ubuntu1~14.04.1) 4.8.5`, and [Travis uses `gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4`](https://travis-ci.org/flexible-collision-library/fcl/jobs/140381252#L727).

I couldn't reproduce the reported problem, and actually don't think it's a compiler problem. It would be nice if anyone can reproduce the problem by creating a test repo or any other way.

**Comment by pbarragan** [comment] 2016-06-29 21:52
@jslee02 I'd be happy to help as the error happens on my system, but I'm not sure how to create a repo that would produce the problem on any system. I can provide any information that's helpful, but if someone could point me to what to provide or how to create said repo, I'd appreciate it as I'm a bit new to how to debug this.

**Comment by jslee02** [comment] 2016-06-30 15:43
For a simple test, can you replace all the `OCTOMAP_VERSION_AT_LEAST(1,8,0)` with `OCTOMAP_MAJOR_VERSION` and let me know what you get?

**Comment by pbarragan** [comment] 2016-06-30 20:23
I made the change, removed the previous build directory, cmake .. in a new build directory and make and it seemed to work just fine. I then ran ./tests/test_fcl_distance and that also worked with no errors. make install also worked fine. Seems like it fixed that part.

**Comment by jvgomez** [comment] 2016-07-03 11:58
A quick note, I think at this point is much easier to follow something like Gazebo guys do:

```
#if GAZEBO_VERSION_MAJOR >=7
....
```

Maybe we should do

#if OCTOMAP_MAJOR_VERSION >= 1
# if OCTOMAP_MINOR_VERSION >= 8
...
# endif
#endif
```

Or just simple collapse all this into a macro `#if OCTOMAP_VERSION_GREATER_1.8`

**Comment by wjwwood** [comment] 2016-07-21 23:45
I believe the pull request I just opened should fix this: https://github.com/flexible-collision-library/fcl/pull/142

Basically, if you already have `fcl` installed, then in certain situations you can get the installed `fcl/config.h` rather than the one generated for the local build. That's why this never showed up in CI.

**Comment by jslee02** [comment] 2016-07-22 02:25
(Reopening as closed automatically when #142 was merged)

@dblanm @pbarragan Could you confirm if #142 works for you?

**Comment by dblanm** [comment] 2016-07-22 07:04
I completley removed fcl and octomap libraries, 
I installed octomap by CI folder and then installed fcl, the problem no longer exits. 
Thank you for the solution.

**Comment by dblanm** [comment] 2016-07-22 07:19
I am testing now fcl octree and octomap using ROS and it compiles, then i think the problem is well solved.

**Comment by jslee02** [comment] 2016-07-24 20:42
Okay, it seems the issue is resolved! Closing.

**Closed by jslee02** 2016-07-24 20:42 UTC

**Comment by k-maheshkumar** [comment] 2018-02-09 10:21
Hey, I just checked out the branch fcl-0.5 and tried to build, but got the same error. Please help to build the package.
Thank you.
