### ISSUE TITLE
Consider "-inl.h" design pattern to reduce compile time for templated code

### ISSUE THREAD

**Issue by sherm1** [flexible-collision-library/fcl#160] opened 2016-08-14 19:50 UTC
After PR #154 lands, most FCL code is templatized by scalar type. In normal use it will almost always be instantiated with `double` (*maybe* `float`). The more elaborate instantiations needed for autodifferentiation will be rare, so most user code needs only declarations for the `T=double` case and doesn't need to have access to the definitions of the templatized methods, which are expensive to compile.

In Drake we use [this design pattern](http://drake.mit.edu/cxx_inl.html) to hide the definitions from compilation units that don't need them. Then we explicitly instantiate the most common `T=double` case in library code. So user code normally includes `blah.h`; code that needs to make its own instantiation includes `blah-inl.h`.

We should consider this for FCL also to lighten the compilation load, reduce code bloat, and hide implementations when possible.

**Comment by jslee02** [comment] 2016-08-14 22:54
I like this idea! I've been looking for a way of reducing the compilation time after I experienced dramatically increased compilation time with #154.

I proposed minimizing exposing API to users using `detail` directory. Accordingly, I would prefer to have the implementation files in `detail` directory. The file name could be either of the same as the declaration file or the declaration file name with a suffix. For the suffix, I would prefer `-impl.h` because `-inl.h` sounds like for inline functions. How do you think?

One concern with this design pattern is that FCL wouldn't be a header-only project, which I was intended for the next work. But now I think reducing compilation time is more worth and don't have a compelling reason for making FCL header-only project.

**Comment by sherm1** [comment] 2016-08-15 00:25
Yeah, I agree `-impl.h` makes more sense than `-inl.h`.

I think with this design pattern FCL *could* be used header-only, if people use the `-impl.h` headers. But most users would probably be glad to link instead to avoid recompiling all that code with every use.

**Comment by jslee02** [comment] 2016-08-15 05:41
We could consider explicitly instantiating for `T=fcl::real` rather than `T=double`, and aliasing `fcl::real` as `double` by default. This would allow us to build FCL instantiated with different type by simply switching the `fcl::real` to the different type.

**Comment by sherm1** [comment] 2016-08-15 06:09
Actually for explicit instantiations it wouldn't be unreasonable to simply instantiate for `float` and `double` both if those are the only common ones. Since the code would just exist once for each in the library the overhead would be minimal. Then I think there would be no need for `fcl::real` and people wouldn't have to try to coordinate that with whatever other packages they are using.

**Comment by sherm1** [comment] 2016-08-15 17:22
@jslee02, Jeremy Nimmer asserts that he used `-inl.h` in Drake because it is sort of an industry standard despite its somewhat-wrong connotation. See RobotLocomotion/drake#3141.

**Comment by jslee02** [comment] 2016-08-16 02:59
If it's an industry standard then I'm okay with it. I don't have a strong preference here.

**Comment by sherm1** [comment] 2016-08-17 20:06
Googling for "template inl.h instantiation" does pull up a lot of uses, including a mention in the Google Style Guide, basically to say "don't do this" (but they aren't talking about this specific problem). `impl.h` definitely doesn't get the same amount of press.

**Comment by scpeters** [comment] 2016-08-18 06:08
Searching the [ubuntu packages database](https://www.google.com/#q=site:packages.ubuntu.com+%22*-inl.h%22), I see it in [nodejs](http://packages.ubuntu.com/xenial/amd64/nodejs-dev/filelist), [unity](http://packages.ubuntu.com/trusty/amd64/libunity-core-6.0-dev/filelist), [gtest](http://packages.ubuntu.com/precise/amd64/libgtest-dev/filelist), and [mongodb](http://packages.ubuntu.com/trusty/amd64/mongodb-dev/filelist). So it is in use in some well-known projects.

**Comment by jslee02** [comment] 2016-08-18 06:15
Interestingly I got 1,260 results for `-impl.h` while got 762 for `-inl.h`.

**Comment by jslee02** [comment] 2016-08-18 06:21
Anyways, I created a [pull request](https://github.com/flexible-collision-library/fcl/pull/165) for this. Feedback is welcome!

**Comment by sherm1** [comment] 2016-08-18 16:20
> Interestingly I got 1,260 results for -impl.h while got 762 results for -inl.h.

I saw that too but then when I looked closer Google had apparently dropped the ".h" and matched lots of things containing the word "implementation"!

**Comment by jslee02** [comment] 2016-09-09 11:49
I believe this is addressed by #165.

**Closed by jslee02** 2016-09-09 11:49 UTC
