### ISSUE TITLE
Build fails: use of undeclared identifier 'ASSERT_DEATH'

### ISSUE THREAD

**Issue by yurivict** [flexible-collision-library/fcl#354] opened 2018-11-20 05:01 UTC
```
/usr/ports/math/fcl/work/fcl-0.5.0-304-g16c193a/test/narrowphase/detail/convexity_based_algorithm/test_gjk_libccd-inl_epa.cpp:428:3: error: use of undeclared identifier 'ASSERT_DEATH'
  ASSERT_DEATH(
  ^
/usr/ports/math/fcl/work/fcl-0.5.0-304-g16c193a/test/narrowphase/detail/convexity_based_algorithm/test_gjk_libccd-inl_epa.cpp:443:3: error: use of undeclared identifier 'ASSERT_DEATH'
  ASSERT_DEATH(
  ^
/usr/ports/math/fcl/work/fcl-0.5.0-304-g16c193a/test/narrowphase/detail/convexity_based_algorithm/test_gjk_libccd-inl_epa.cpp:504:3: error: use of undeclared identifier 'ASSERT_DEATH'
  ASSERT_DEATH(
  ^
3 errors generated.
```

FreeBSD 11.2 amd64
googletest-1.8.1

**Comment by jamiesnape** [comment] 2019-01-16 13:43
Duplicate of #358.

**Closed by jamiesnape** 2019-01-16 13:43 UTC
