### ISSUE TITLE
error: use of undeclared identifier 'ASSERT_DEATH'

### ISSUE THREAD

**Issue by yurivict** [flexible-collision-library/fcl#396] opened 2019-04-24 06:46 UTC
Build fails on FreeBSD:
```
/usr/ports/math/fcl/work/fcl-0.5.0-320-g09f846c/test/narrowphase/detail/convexity_based_algorithm/test_gjk_libccd-inl_gjk_doSimplex2.cpp:289:3: error: use of undeclared identifier 'ASSERT_DEATH'
  ASSERT_DEATH(doSimplex2(&line_, &dir_),
  ^
/usr/ports/math/fcl/work/fcl-0.5.0-320-g09f846c/test/narrowphase/detail/convexity_based_algorithm/test_gjk_libccd-inl_gjk_doSimplex2.cpp:303:3: error: use of undeclared identifier 'ASSERT_DEATH'
  ASSERT_DEATH(doSimplex2(&line_, &dir_),
  ^
/usr/ports/math/fcl/work/fcl-0.5.0-320-g09f846c/test/narrowphase/detail/convexity_based_algorithm/test_gjk_libccd-inl_gjk_doSimplex2.cpp:317:3: error: use of undeclared identifier 'ASSERT_DEATH'
  ASSERT_DEATH(doSimplex2(&line_, &dir_),
  ^
3 errors generated.
```

rev.09f846c

**Comment by SeanCurtis-TRI** [comment] 2019-04-24 13:24
I'd bet this is a case of what version of gtest is being pulled.  :-/ The baseline version is already quite antiquated; FreeBSD must pull an even older version.  Can you determine what version of gtest you have?

Possible solutions:

1. Reformulate the test to not require `ASSERT_DEATH`.
2. Nail down the gtest requirement explicitly rather than relying on system installs.

**Comment by SeanCurtis-TRI** [comment] 2019-04-24 13:36
Try changing those lines to `ASSERT_DEATH_IF_SUPPORTED` and let me know if that gets you over the hurdle.

**Comment by yurivict** [comment] 2019-04-24 16:29
googletest-1.8.1 - the latest version.

**Comment by yurivict** [comment] 2019-04-24 16:34
I got this trying the latest revision, which I don't really need now.
I'd wait for the release then.

**Comment by SeanCurtis-TRI** [comment] 2019-04-24 16:50
Any word on changing `ASSERT_DEATH` to `ASSERT_DEATH_IF_SUPPORTED`? If it works for you, then we can mindlessly PR that and worry about when and where it's supported outside of CI later.

**Comment by yurivict** [comment] 2019-04-24 22:24
nope:
```
/usr/ports/math/fcl/work/fcl-0.5.0-320-g09f846c/test/narrowphase/detail/convexity_based_algorithm/test_gjk_libccd-inl_gjk_doSimplex2.cpp:289:3: error: use of undeclared identifier 'ASSERT_DEATH_IF_SUPPORTED'
  ASSERT_DEATH_IF_SUPPORTED(doSimplex2(&line_, &dir_),
  ^
```

**Comment by SeanCurtis-TRI** [comment] 2019-04-26 14:02
Blast! This is going to require a lot more investigation into FreeBSD and gtest (made all the more challenging as I don't currently have anything running FreeBSD.)

On the other hand, the simplest solution is to change the [`assert`](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L335) that is being tested here into a DEBUG-build exception. Detecting a thrown exception is obviously more compatible with your environment.

How much is this build problem inconveniencing you?

**Comment by yurivict** [comment] 2019-04-26 15:36
Or you can just switch to the latest released ```googletest``` because these macros seem to come from it.

**Comment by SeanCurtis-TRI** [comment] 2019-04-27 03:18
The challenge is that they work for me, they work in CI in windows, Mac OS, and Linux. They only seem to not work for you. And that's the mystery.

**Comment by yurivict** [comment] 2019-04-27 05:11
Install it in the VM then.

**Comment by jwnimmer-tri** [comment] 2021-09-15 21:49
@sherm1 please close as duplicate of #443?

**Closed** 2021-09-15 22:01 UTC
